#!/bin/sh
mount proc

# Set the initial date
export $(cat /proc/cmdline | tr ' ' '\n' | grep "^jido_builddate=")
if [ ! -z ${jido_builddate-} ]; then
  [ "$jido_builddate" -lt `/bin/date +%s` ] || /bin/date +%s -s @${jido_builddate}
fi

# Enable multiple virtual terminals if requested
grep -qw multivt /proc/cmdline && sed -i s/^#tty/tty/ /etc/inittab

# Set up RAM filesystem with optimized size for unikernel
inodes=`grep MemFree /proc/meminfo | awk '{print $2/3}' | cut -d. -f1`
mount / -o remount,size=90%,nr_inodes=$inodes

umount proc
exec /sbin/init
